#!/bin/bash
set -e

export a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; BASE_DIR=$(cd $a; pwd)
cd ${BASE_DIR}
source ${BASE_DIR}/scripts/set_env.sh

case "$ARG1" in
  load)
    ${BASE_DIR}/scripts/load.sh
    ;;
  test)
    ${BASE_DIR}/scripts/test.sh
    ;;
  install)
    ${BASE_DIR}/scripts/install_deps.erl
    ${BASE_DIR}/scripts/refresh.sh
    ;;
  *)
    echo "Usage: moongate load|test|install"
    exit 1
    ;;
esac
