#!/bin/bash
set -e

# Prepare environment
export a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; BASE_DIR=$(cd $a; pwd)
export ELIXIR_DIR=${BASE_DIR}/.moongate/elixir/bin
export NODE_DIR=${BASE_DIR}/.moongate/node/bin
export REDIS_DIR=${BASE_DIR}/.moongate/redis/src
export MODIFIED_PATH=${ELIXIR_DIR}:${REDIS_DIR}:${NODE_DIR}:${PATH}
export GAME_PATH=${2:-games/orbs}
export MOONGATE_GAME=$(basename $GAME_PATH)
export MOONGATE_GAME_PATH=${GAME_PATH}
export PATH=${MODIFIED_PATH}

cd ${BASE_DIR}

case "$1" in
  load)
    export MOONGATE_ENV=${MIX_ENV:-dev}
    elixir scripts/moongate_config.exs
    echo -e "Loading \033[0;32m${GAME_PATH}\033[0m"
    mix clean
    elixir scripts/gen_rustler_bridge.exs
    redis-server --daemonize yes
    iex --dot-iex .iex.moongate.exs -S mix
    elixir scripts/kill_trapped_pids.exs
    ;;
  test)
    export MOONGATE_ENV=test
    MIX_ENV=test mix clean
    MIX_ENV=test mix test
    ;;
  install)
    export MOONGATE_ENV=dev
    ${BASE_DIR}/scripts/install.erl
    ;;
  cmd)
    shift
    shift
    eval "$*"
    ;;
  *)
    echo "Usage: moongate load|test|install|cmd"
    exit 1
    ;;
esac
